version: "3.7"
services:
  flow-forecast:
    build:
      context: .
      dockerfile: Dockerfile
    image: flow-forecast
    container_name: flow-forecast
    ports:
      - "3000:3000"
    volumes:
      - .:/flow-forecast